// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schnittstellenzentrale.Infrastructure.Data;

#nullable disable

namespace Schnittstellenzentrale.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523000000_AddParentGroupIdToEndpointGroup")]
    partial class AddParentGroupIdToEndpointGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InterfaceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationGroupId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.ApplicationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ApplicationGroups");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthenticationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("BodyMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndpointGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EndpointGroupId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("EndpointGroups");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("EndpointHeaders");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointQueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("EndpointQueryParameters");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.Application", b =>
                {
                    b.HasOne("Schnittstellenzentrale.Core.Models.ApplicationGroup", "ApplicationGroup")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicationGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationGroup");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.Endpoint", b =>
                {
                    b.HasOne("Schnittstellenzentrale.Core.Models.Application", "Application")
                        .WithMany("Endpoints")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schnittstellenzentrale.Core.Models.EndpointGroup", "EndpointGroup")
                        .WithMany("Endpoints")
                        .HasForeignKey("EndpointGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Application");

                    b.Navigation("EndpointGroup");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointGroup", b =>
                {
                    b.HasOne("Schnittstellenzentrale.Core.Models.Application", "Application")
                        .WithMany("EndpointGroups")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schnittstellenzentrale.Core.Models.EndpointGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointHeader", b =>
                {
                    b.HasOne("Schnittstellenzentrale.Core.Models.Endpoint", "Endpoint")
                        .WithMany("Headers")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointQueryParameter", b =>
                {
                    b.HasOne("Schnittstellenzentrale.Core.Models.Endpoint", "Endpoint")
                        .WithMany("QueryParameters")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.Application", b =>
                {
                    b.Navigation("EndpointGroups");

                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.ApplicationGroup", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.Endpoint", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });

            modelBuilder.Entity("Schnittstellenzentrale.Core.Models.EndpointGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
